    - name: Update Branch
        env:
          NAME: ${{ secrets.USER_NAME }}
          EMAIL: ${{ secrets.USER_EMAIL }}
<<<<<<< HEAD
        run: make update-branch USER_NAME=$NAME USER_EMAIL=$EMAIL
=======
        run: make update-branch USER_NAME=$NAME USER_EMAIL=$EMAIL
>>>>>>> e9b6d2909fcddb28486064df9ea6e230ab0ec2a5
